# Inventaire Ansible pour déploiement Prestashop + MySQL
# Architecture: 2 VMs distinctes

[mysql_server]
db ansible_host=192.168.56.11 ansible_user=vagrant ansible_connection=local

[web_server]
web ansible_host=192.168.56.12 ansible_user=vagrant ansible_ssh_pass=vagrant

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
